package nl.tudelft.oopp.demo.config;

import nl.tudelft.oopp.demo.entities.Room;
import nl.tudelft.oopp.demo.repositories.RoomRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.List;

@Configuration
public class RoomConfig {

    @Bean
    CommandLineRunner commandLineRunner(RoomRepository repository) {
        return args -> {
            // id will be generated by DB!
            Room LAY1 = new Room(
                    1,
                    LocalDateTime.of(2021, Month.APRIL, 16, 8, 45, 00 ),
                    "Linear Algebra");

            Room IDMY1 = new Room(
                    2,
                    LocalDateTime.of(2021, Month.APRIL, 17, 14, 00, 00 ),
                    "Information and Database Management");

            Room OOPPY1 = new Room(
                    3,
                    LocalDateTime.of(2021, Month.APRIL, 17, 12, 45, 00 ),
                    "OOP Project");

            repository.saveAll(List.of(LAY1, IDMY1, OOPPY1));
        };
    }

}
